name = "Gauntlet"
uuid = "63b46612-4817-4105-9884-ec370fe8c371"
authors = ["Alphonsus Adu-Bredu"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
